<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class ProductoAcabadoSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return vonombrecorto
     */
    public function run()
    {
        \DB::table('producto_acabados')->delete();

        \DB::table('producto_acabados')->insert([
            ['nombrecorto'=>'AVY_3026','nombre'=>'AVERY MPI3026'],
            ['nombrecorto'=>'NOV_6030','nombre'=>'NOVA PRISMA 6030'],
            ['nombrecorto'=>'GLR_50001','nombre'=>'GLASS RITRAMA 50001'],
            ['nombrecorto'=>'BACK','nombre'=>'BACKLITE'],

            // ['nombrecorto'=>'AVY_3026','nombre'=>'AVERY MPI3026'],
            // ['nombrecorto'=>'NOV_6030','nombre'=>'NOVA PRISMA 6030'],
            // ['nombrecorto'=>'NOV_40001','nombre'=>'NOVA PRISMA ALTA GAMA 40001 '],
            // ['nombrecorto'=>'NOV_40003','nombre'=>'NOVA PRISMA ALTA ADH 40003'],
            // ['nombrecorto'=>'GLR_50001','nombre'=>'GLASS RITRAMA 50001'],
            // ['nombrecorto'=>'GLR_50400','nombre'=>'GLASS RITRAMA 50400'],
            // ['nombrecorto'=>'MTL_979860','nombre'=>'MAC TAC 979860 LIGHT DIFUSER'],
            // ['nombrecorto'=>'MTW_982800','nombre'=>'MAC TAC 982800 MATT WHITE'],
            // ['nombrecorto'=>'MTB_988800','nombre'=>'MAC TAC 988800 MATT BLACK'],
            // ['nombrecorto'=>'ORO_6510038','nombre'=>'ORACAL RED ORANGE FLUORESCENTE'],
            // ['nombrecorto'=>'ORR_6510046','nombre'=>'ORACAL ROSA FLUORESCENTE'],
            // ['nombrecorto'=>'MAG_AGF','nombre'=>'MAGENTA AGFA'],
            // ['nombrecorto'=>'2C','nombre'=>'2CARAS'],
            // ['nombrecorto'=>'AVY_501EF','nombre'=>'AVERY MATT WHITE 501EF'],
            // ['nombrecorto'=>'AVY_502EF','nombre'=>'AVERY MATT BLACK 502EF'],
            // ['nombrecorto'=>'AVY_503EF','nombre'=>'AVERY 503EF MATT GERANIUM RED '],
            // ['nombrecorto'=>'AVY_504EF','nombre'=>'AVERY PIMROSE YELLOW 504EF'],
            // ['nombrecorto'=>'AVY_507EF','nombre'=>'AVERY MATT BROWN 507EF'],
            // ['nombrecorto'=>'AVY_519EF','nombre'=>'AVERY MATT RED 519EF'],
            // ['nombrecorto'=>'AVY_524EF','nombre'=>'AVERY MATT MAGENTA 524EF'],
            // ['nombrecorto'=>'BOS_89701E','nombre'=>'BRITE OVEREALL SILVER DURABLE'],
            // ['nombrecorto'=>'AGF','nombre'=>'AGFA'],
            // ['nombrecorto'=>'ADH','nombre'=>'ADHESIVA'],
            // ['nombrecorto'=>'ANT','nombre'=>'ANTnombrecortoESLIZANTE'],
            // ['nombrecorto'=>'BOL','nombre'=>'BOLSA 1KG'],
            // ['nombrecorto'=>'K_AGF','nombre'=>'BLACK AGFA'],
            // ['nombrecorto'=>'BACK','nombre'=>'BACKLITE'],
            // ['nombrecorto'=>'BC','nombre'=>'BLACK CANON'],
            // ['nombrecorto'=>'BD','nombre'=>'BLACK DURST'],
            // ['nombrecorto'=>'BLACK','nombre'=>'NEGRO'],
            // ['nombrecorto'=>'BO','nombre'=>'BORDELESS  OFIJET'],
            // ['nombrecorto'=>'BR','nombre'=>'BRILLO'],
            // ['nombrecorto'=>'CAN','nombre'=>'CANON'],
            // ['nombrecorto'=>'CHO','nombre'=>'CHOPO'],
            // ['nombrecorto'=>'COL','nombre'=>'COLOR'],
            // ['nombrecorto'=>'CUE','nombre'=>'CUERO'],
            // ['nombrecorto'=>'CYA_agf','nombre'=>'CYAN AGFA'],
            // ['nombrecorto'=>'CYA_CAN','nombre'=>'CYAN CANON'],
            // ['nombrecorto'=>'CYA_DUR','nombre'=>'CYAN DURST'],
            // ['nombrecorto'=>'CYA_OFI','nombre'=>'CYAN OFIJET'],
            // ['nombrecorto'=>'COM','nombre'=>'en blanco)'],
            // ['nombrecorto'=>'CEP','nombre'=>'CEPILLADO'],
            // ['nombrecorto'=>'CRE','nombre'=>'CREPE'],
            // ['nombrecorto'=>'CRU','nombre'=>'CRUDO'],
            // ['nombrecorto'=>'CAS','nombre'=>'CANALSIMPLE'],
            // ['nombrecorto'=>'DUR','nombre'=>'DURST'],
            // ['nombrecorto'=>'DRY_DAWBL995','nombre'=>'DRY APPLY WBL995'],
            // ['nombrecorto'=>'DCA_3MFM1750','nombre'=>'3MFM1750 DOBLE CARA'],
            // ['nombrecorto'=>'DCA','nombre'=>'DOBLE CARA'],
            // ['nombrecorto'=>'DUG','nombre'=>'DUGOPA'],
            // ['nombrecorto'=>'E2C_MAT','nombre'=>'ESTUCADO 2 CARAS MATE'],
            // ['nombrecorto'=>'EIN','nombre'=>'EXTRUSION INCOLORO'],
            // ['nombrecorto'=>'ERA_230120W','nombre'=>'TOTAL ERAZE 23012C BLANCO'],
            // ['nombrecorto'=>'EWO','nombre'=>'EXTRUSION BLANCO OPACO'],
            // ['nombrecorto'=>'EWOP','nombre'=>'EXTRUSION BLANCO OPAL'],
            // ['nombrecorto'=>'FBR','nombre'=>'FUJI BRILLO'],
            // ['nombrecorto'=>'FMT','nombre'=>'FUJI MATE'],
            // ['nombrecorto'=>'GEN','nombre'=>'GENESIS'],
            // ['nombrecorto'=>'GO','nombre'=>'GREEN OFIJET'],
            // ['nombrecorto'=>'IN','nombre'=>'INCOLORO'],
            // ['nombrecorto'=>'KFT','nombre'=>'KRAFT'],
            // ['nombrecorto'=>'KNV','nombre'=>'KRAFT NATURAL VERJURADO 90'],
            // ['nombrecorto'=>'KVH','nombre'=>'VERJURADO HOLANDES'],
            // ['nombrecorto'=>'KVR','nombre'=>'VERJURADO RADIOGRAFIA'],
            // ['nombrecorto'=>'LCA','nombre'=>'LIGHT CYAN AGFA'],
            // ['nombrecorto'=>'LCO','nombre'=>'LIGHT CYAN OFIJET'],
            // ['nombrecorto'=>'LKO','nombre'=>'LIGHT BACK OFIJET'],
            // ['nombrecorto'=>'LMA','nombre'=>'LIGHT MAGENTA AGFA'],
            // ['nombrecorto'=>'LMO','nombre'=>'LIGHT MAGENTA OFIJET'],
            // ['nombrecorto'=>'MBR','nombre'=>'MONOMERICO BRILLO'],
            // ['nombrecorto'=>'MC','nombre'=>'MAGENTA CANON'],
            // ['nombrecorto'=>'MD','nombre'=>'MAGENTA DURST'],
            // ['nombrecorto'=>'MKO','nombre'=>'MATTE BACK OFIJET'],
            // ['nombrecorto'=>'MMT','nombre'=>'MONOMERICO MATE'],
            // ['nombrecorto'=>'MS55','nombre'=>'MS55'],
            // ['nombrecorto'=>'MT','nombre'=>'MATE'],
            // ['nombrecorto'=>'N','nombre'=>'NORMAL'],
            // ['nombrecorto'=>'O','nombre'=>'OFIJET'],
            // ['nombrecorto'=>'OO','nombre'=>'ORANGE OFIJET'],
            // ['nombrecorto'=>'ORO','nombre'=>'ORO'],
            // ['nombrecorto'=>'OW','nombre'=>'OFFSET BLANCO'],
            // ['nombrecorto'=>'PA','nombre'=>'PRIMER AGFA'],
            // ['nombrecorto'=>'PBR','nombre'=>'POLIMERICO BRILLO'],
            // ['nombrecorto'=>'PGH','nombre'=>'PAPER GRAPHICS'],
            // ['nombrecorto'=>'PKO','nombre'=>'PHOTO BACK OFIJET'],
            // ['nombrecorto'=>'PLATA','nombre'=>'PLATA'],
            // ['nombrecorto'=>'PPP','nombre'=>'PRECINTO POLIPROPILENO TRANSP'],
            // ['nombrecorto'=>'PSU','nombre'=>'POLIMERICO SATIN UVA'],
            // ['nombrecorto'=>'PTEX','nombre'=>'PLATA EXTERIOR'],
            // ['nombrecorto'=>'PTIN','nombre'=>'PLATA INTERIOR'],
            // ['nombrecorto'=>'PW','nombre'=>'POLITENO BLANCO'],
            // ['nombrecorto'=>'RED','nombre'=>'ROJO'],
            // ['nombrecorto'=>'SAC','nombre'=>'SACO'],
            // ['nombrecorto'=>'SFR','nombre'=>'SOLATUV FR'],
            // ['nombrecorto'=>'SLK','nombre'=>'SILK'],
            // ['nombrecorto'=>'STD','nombre'=>'STANDARD'],
            // ['nombrecorto'=>'TMTBR','nombre'=>'TRANSPARENTE MATE BRILLO'],
            // ['nombrecorto'=>'TMTMT','nombre'=>'TRANSPARENTE MATE MATE'],
            // ['nombrecorto'=>'TR','nombre'=>'TRANSPARENTE'],
            // ['nombrecorto'=>'TW','nombre'=>'TRASERA BLANCA'],
            // ['nombrecorto'=>'UC','nombre'=>'ULTRA CRISTALINO'],
            // ['nombrecorto'=>'UNI','nombre'=>'UNIVERSAL'],
            // ['nombrecorto'=>'UW','nombre'=>'UNIVERSAL BLANCO'],
            // ['nombrecorto'=>'VAN','nombre'=>'VILEDA ANTIGRAFFITI'],
            // ['nombrecorto'=>'VBR','nombre'=>'VELLEDA CB90 BRILLO'],
            // ['nombrecorto'=>'VMO','nombre'=>'VIVnombrecorto MAGENTA OFIJET'],
            // ['nombrecorto'=>'VMT','nombre'=>'VELLEDA CB75 MATE'],
            // ['nombrecorto'=>'VO','nombre'=>'VIOLET OFIJET'],
            // ['nombrecorto'=>'VPO','nombre'=>'PARA OPACAR'],
            // ['nombrecorto'=>'W','nombre'=>'BLANCO'],
            // ['nombrecorto'=>'WA','nombre'=>'WHITE AGFA'],
            // ['nombrecorto'=>'WBR','nombre'=>'BLANCO BRILLO'],
            // ['nombrecorto'=>'WBRH','nombre'=>'BLANCO BRILLO HOP'],
            // ['nombrecorto'=>'WC','nombre'=>'WHITE CANON'],
            // ['nombrecorto'=>'WE','nombre'=>'BLANCO ESTUCADO'],
            // ['nombrecorto'=>'WE2C','nombre'=>'BLANCO ESTUCADO 2 CARAS'],
            // ['nombrecorto'=>'WFW','nombre'=>'BLANCO KRAFT BLANCO'],
            // ['nombrecorto'=>'WKW','nombre'=>'BLANCO NEGRO BLANCO'],
            // ['nombrecorto'=>'WMT','nombre'=>'BLANCO MATE'],
            // ['nombrecorto'=>'WMTADH','nombre'=>'BLANCO MATE ADHESIVO'],
            // ['nombrecorto'=>'WMTH','nombre'=>'BLANCO MATE HOP'],
            // ['nombrecorto'=>'WOP','nombre'=>'BLANCO OPAL'],
            // ['nombrecorto'=>'WPT','nombre'=>'WALL PRINT  IJ480'],
            // ['nombrecorto'=>'WTRAS','nombre'=>'BLANCO TRASLUCnombrecortoO'],
            // ['nombrecorto'=>'WWW','nombre'=>'BLANCO BLANCO BLANCO'],
            // ['nombrecorto'=>'YA','nombre'=>'YELLOW AGFA'],
            // ['nombrecorto'=>'YC','nombre'=>'YELLOW CANON'],
            // ['nombrecorto'=>'YD','nombre'=>'YELLOW DURST'],
            // ['nombrecorto'=>'YO','nombre'=>'YELLOW OFIJET'],
            // ['nombrecorto'=>'Z','nombre'=>'KATZ'],
        ]);
    }
}
